### ISSUE TITLE
color-console is not accessible

### ISSUE THREAD

**Issue by ficapy** [nazmulidris/idea-plugin-example#1]
Thank you, very good tutorial, but I'm getting the following error while building
```
Could not HEAD 'https://maven.pkg.github.com/nazmulidris/color-console/com/developerlife/color-console/1.0/color-console-1.0.pom'. Received status code 400 from server: Bad Request
```

maybe this password is not correct
```
repositories {
  maven {
    name = "GitHubPackages"
    url = uri("https://maven.pkg.github.com/nazmulidris/color-console")
    credentials {
      username = System.getenv("GITHUB_PACKAGES_USERID") ?: "nazmulidris"
      // Safe to share the password since it is a `read:package` scoped token.
      password = System.getenv("GITHUB_PACKAGES_IMPORT_TOKEN") ?: "22e9ba0d47c3e9116a2f1023867a1985beebfb60"
    }
  }
}
```

**Comment by nazmulidris** [comment]
@ficapy Thanks for the error message. I have been seeing this too. This is due to the fact that Github Package Registry does not really support [unauthenticated downloads](https://github.community/t/download-from-github-package-registry-without-authentication/14407/93) 😭. 

I have to move the `color-console` dependency to some other provider. I will reply on this comment when I have figured out where to move it to.

For now, you can just download https://github.com/nazmulidris/color-console/tree/main/src/main/kotlin/color_console_log this file to the source for `idea-plugin-example`, and remove the dep on `color-console` in `build.gradle.kts`.

**Comment by nazmulidris** [comment]
@ficapy I just published the `color-console` dependency on JitPack.

You can use it now by following the directions on this page https://jitpack.io/#nazmulidris/color-console/1.0.0

If you can wait an hour, then I will update the `build.gradle.kts` in this repo so you can just do a git pull then 👍🏽.

**Comment by nazmulidris** [comment]
@ficapy This [commit](https://github.com/nazmulidris/color-console/commit/58e80f8ae62f2ef1bfb930a262c5278d5a82aefc) fixes the issue. Please do a `git pull` and you will have the changes to use JitPack instead of GPR for the `color-console` dep.
